name: CatchTail
version: ${project.version}
main: com.cragon.catchtail.CatchTail
api-version: 1.13
depend: [MinigameCore]
authors: [CraftyDragon678]
description: catch tail!
website: https://github.com/CraftyDragon678/
